name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate Environment File
        run: |
          echo "NEXT_PUBLIC_APP_NAME=${{ secrets.NEXT_PUBLIC_APP_NAME }}" >> .env
          echo "NEXT_PUBLIC_STANDARD_CHAT_API_URL=${{ secrets.NEXT_PUBLIC_STANDARD_CHAT_API_URL }}" >> .env
          echo "NEXT_PUBLIC_MULTI_AGENT_CHAT_API_URL=${{ secrets.NEXT_PUBLIC_MULTI_AGENT_CHAT_API_URL }}" >> .env
          echo "NEXT_PUBLIC_CHAT_HISTORY_API_URL=${{ secrets.NEXT_PUBLIC_CHAT_HISTORY_API_URL }}" >> .env
          echo "NEXT_PUBLIC_STANDARD_CHAT_API_MODE=${{ secrets.NEXT_PUBLIC_STANDARD_CHAT_API_MODE }}" >> .env
          echo "NEXT_PUBLIC_MULTI_AGENT_CHAT_API_MODE=${{ secrets.NEXT_PUBLIC_MULTI_AGENT_CHAT_API_MODE }}" >> .env
          echo "NEXT_PUBLIC_MULTI_AGENT_RESPONSE_MODE=${{ secrets.NEXT_PUBLIC_MULTI_AGENT_RESPONSE_MODE }}" >> .env
          echo "NEXT_PUBLIC_CHAT_HISTORY_MODE=${{ secrets.NEXT_PUBLIC_CHAT_HISTORY_MODE }}" >> .env
      
      - name: Build and test
        run: |
          npm run build
          npm test
        env:
          NODE_ENV: production
          NEXT_PUBLIC_APP_NAME: ${{ secrets.NEXT_PUBLIC_APP_NAME }}
          NEXT_PUBLIC_STANDARD_CHAT_API_URL: ${{ secrets.NEXT_PUBLIC_STANDARD_CHAT_API_URL }}
          NEXT_PUBLIC_MULTI_AGENT_CHAT_API_URL: ${{ secrets.NEXT_PUBLIC_MULTI_AGENT_CHAT_API_URL }}
          NEXT_PUBLIC_CHAT_HISTORY_API_URL: ${{ secrets.NEXT_PUBLIC_CHAT_HISTORY_API_URL }}
          NEXT_PUBLIC_STANDARD_CHAT_API_MODE: ${{ secrets.NEXT_PUBLIC_STANDARD_CHAT_API_MODE }}
          NEXT_PUBLIC_MULTI_AGENT_CHAT_API_MODE: ${{ secrets.NEXT_PUBLIC_MULTI_AGENT_CHAT_API_MODE }}
          NEXT_PUBLIC_MULTI_AGENT_RESPONSE_MODE: ${{ secrets.NEXT_PUBLIC_MULTI_AGENT_RESPONSE_MODE }}
          NEXT_PUBLIC_CHAT_HISTORY_MODE: ${{ secrets.NEXT_PUBLIC_CHAT_HISTORY_MODE }}
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "out"
        env:
          NODE_ENV: production
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close" 